name: django_een1037_starter_project
services:
  main:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://myappdbuser:myappdbpass@db:5432/myappdb
    depends_on:
      db:
        condition: service_started
    volumes:
      - myapp-storage:/app/storage

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: myappdbuser
      POSTGRES_PASSWORD: myappdbpass
      POSTGRES_DB: myappdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  myapp-storage:
