# Generated by Django 5.1.7 on 2025-03-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='myapp_upload/')),
                ('created', models.DateTimeField()),
                ('last_edited', models.DateTimeField()),
            ],
        ),
    ]
