# Generated by Django 5.1.7 on 2026-03-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_newslettersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscription',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
